#!/bin/bash

# Get external IP, and add to allow list for security group
EXTERNAL_IP=$(dig TXT +short o-o.myaddr.l.google.com @ns1.google.com | awk -F'"' '{ print $2}')
sed -i "s|^ip_whitelist.*|ip_whitelist            = [\"$EXTERNAL_IP/32\"] #Change this to your public ip/32|" terraform.tfvars

# Apply Terraform state
terraform init
terraform apply --auto-approve
