#!/bin/bash

# Get external IP
EXTERNAL_IP=$(dig TXT +short o-o.myaddr.l.google.com @ns1.google.com | awk -F'"' '{ print $2}')
sed -i "s|^ip_whitelist.*|ip_whitelist            = [\"$EXTERNAL_IP/32\"] #Change this to your public ip/32|" terraform.tfvars

# Set to Latest AMI
aws ec2 describe-images --executable-users self | jq -r '.Images[] | select(.Name | contains("rc.2")).ImageId' | xargs -I {} sudo sed -i 's/ami                     = "ami-.*"/ami                     = "{}"/' terraform.tfvars

# Apply Terraform state
terraform init
terraform apply --auto-approve
