variable "region" {}
variable "project" {}
variable "shared_credentials_file" {}
variable "host_vpc_name" {}
variable "so_vpc_name" {}
variable "so_subnet_cidr" {}
variable "host_subnet_cidr" {}
variable "ip_whitelist" {}
variable "public_key_name" {}
variable "public_key_path" {}
variable "private_key_path" {}
variable "profile" {}
variable "so_username" {}
variable "zone" {}
variable "so_machine_type" {}
variable "so_machine_name" {}
variable "so_image_family" {}
variable "so_image_project" {}
variable "so_image_size" {}
